#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
#    username: root
#    password:
#  jpa:
#    database: mysql
#    show-sql: true
#    #Hibernate dll
#    hibernate:
#      ddl-auto: update
#      naming:
#        strategy: org.hibernate.cfg.ImprovedNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
