spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
  jpa:
    database: mysql
    show-sql: true
    #Hibernate dll
    hibernate:
    #自动创建建表语句
      ddl-auto: update
#      在hibernate5中被删除了
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy  z

      #spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
